//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziyi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ziyi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;keyboard&gt;
        ///  &lt;panel name=&quot;Word Complete&quot; width=&quot;100&quot; height=&quot;240&quot;&gt;
        ///    &lt;WordCompleteKey&gt;
        ///      &lt;left&gt;0&lt;/left&gt;
        ///      &lt;top&gt;0&lt;/top&gt;
        ///      &lt;width&gt;100&lt;/width&gt;
        ///      &lt;height&gt;40&lt;/height&gt;
        ///    &lt;/WordCompleteKey&gt;
        ///    &lt;WordCompleteKey&gt;
        ///      &lt;left&gt;0&lt;/left&gt;
        ///      &lt;top&gt;40&lt;/top&gt;
        ///      &lt;width&gt;100&lt;/width&gt;
        ///      &lt;height&gt;40&lt;/height&gt;
        ///    &lt;/WordCompleteKey&gt;
        ///    &lt;WordCompleteKey&gt;
        ///      &lt;left&gt;0&lt;/left&gt;
        ///      &lt;top&gt;80&lt;/top&gt;
        ///      &lt;width&gt;100&lt;/width&gt;
        ///      &lt;height&gt;40&lt;/height&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_kbd {
            get {
                return ResourceManager.GetString("default_kbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;dictionary&gt;
        ///  &lt;settings&gt;
        ///    &lt;case_sensitive&gt;false&lt;/case_sensitive&gt;
        ///    &lt;valid_characters&gt;-ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz&lt;/valid_characters&gt;
        ///    &lt;reset_characters&gt;	
        ///        /// !&quot;#$%&amp;amp;()*+,./:&amp;lt;?@[\]^`{|}&lt;/reset_characters&gt;
        ///  &lt;/settings&gt;
        ///  &lt;word&gt;
        ///    &lt;term&gt;about&lt;/term&gt;
        ///    &lt;frequency&gt;0&lt;/frequency&gt;
        ///  &lt;/word&gt;
        ///  &lt;word&gt;
        ///    &lt;term&gt;above&lt;/term&gt;
        ///    &lt;frequency&gt;0&lt;/frequency&gt;
        ///  &lt;/word&gt;
        ///  &lt;word&gt;
        ///    &lt;term&gt;aboard&lt;/term&gt;
        ///    &lt;frequency&gt;0&lt;/freque [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionary_en {
            get {
                return ResourceManager.GetString("dictionary_en", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Keyboard {
            get {
                object obj = ResourceManager.GetObject("Keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press01 {
            get {
                return ResourceManager.GetStream("press01", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press02 {
            get {
                return ResourceManager.GetStream("press02", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press03 {
            get {
                return ResourceManager.GetStream("press03", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press04 {
            get {
                return ResourceManager.GetStream("press04", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press05 {
            get {
                return ResourceManager.GetStream("press05", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream press06 {
            get {
                return ResourceManager.GetStream("press06", resourceCulture);
            }
        }
    }
}
