//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziyi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dictionary.en.xml")]
        public string DefaultDictionaryFile {
            get {
                return ((string)(this["DefaultDictionaryFile"]));
            }
            set {
                this["DefaultDictionaryFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RepeatInitialDelay {
            get {
                return ((int)(this["RepeatInitialDelay"]));
            }
            set {
                this["RepeatInitialDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RepeatRate {
            get {
                return ((int)(this["RepeatRate"]));
            }
            set {
                this["RepeatRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ForceTopmostRate {
            get {
                return ((int)(this["ForceTopmostRate"]));
            }
            set {
                this["ForceTopmostRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kbd.xml")]
        public string KeyboardLastUsedFile {
            get {
                return ((string)(this["KeyboardLastUsedFile"]));
            }
            set {
                this["KeyboardLastUsedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordCompleteEnable {
            get {
                return ((bool)(this["WordCompleteEnable"]));
            }
            set {
                this["WordCompleteEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddSpaceOnTextSimulation {
            get {
                return ((bool)(this["AddSpaceOnTextSimulation"]));
            }
            set {
                this["AddSpaceOnTextSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceTopmostOnActiveWindowChange {
            get {
                return ((bool)(this["ForceTopmostOnActiveWindowChange"]));
            }
            set {
                this["ForceTopmostOnActiveWindowChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public ushort NewWordAdditionTheshold {
            get {
                return ((ushort)(this["NewWordAdditionTheshold"]));
            }
            set {
                this["NewWordAdditionTheshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveDictionaryOnExit {
            get {
                return ((bool)(this["SaveDictionaryOnExit"]));
            }
            set {
                this["SaveDictionaryOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAeroGlass {
            get {
                return ((bool)(this["EnableAeroGlass"]));
            }
            set {
                this["EnableAeroGlass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KeyboardLeft {
            get {
                return ((double)(this["KeyboardLeft"]));
            }
            set {
                this["KeyboardLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KeyboardTop {
            get {
                return ((double)(this["KeyboardTop"]));
            }
            set {
                this["KeyboardTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KeyboardWidth {
            get {
                return ((double)(this["KeyboardWidth"]));
            }
            set {
                this["KeyboardWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KeyboardHeight {
            get {
                return ((double)(this["KeyboardHeight"]));
            }
            set {
                this["KeyboardHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTypingSound {
            get {
                return ((bool)(this["EnableTypingSound"]));
            }
            set {
                this["EnableTypingSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Input.MouseButton PrimaryInputTrigger {
            get {
                return ((global::System.Windows.Input.MouseButton)(this["PrimaryInputTrigger"]));
            }
            set {
                this["PrimaryInputTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Input.MouseButton SecondaryInputTrigger {
            get {
                return ((global::System.Windows.Input.MouseButton)(this["SecondaryInputTrigger"]));
            }
            set {
                this["SecondaryInputTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThemeLastUsedFile {
            get {
                return ((string)(this["ThemeLastUsedFile"]));
            }
            set {
                this["ThemeLastUsedFile"] = value;
            }
        }
    }
}
